name: bulk-rna-seq-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sra-tools=2.11.0
  - nextflow=21.0.4
  - python=3.9.2
  - r-base=4.0.2
  - r-dplyr=1.0.4
  - r-readr=1.5.0
  - bioconductor-tximport=1.18.0
  - bioconductor-genomicfeatures=1.42.0
  - rsem=1.3.3
  - salmon=1.4.0
  - fastp=0.20.1
  - star=2.7.8a
  - picard-slim=2.25.1
  - multiqc=1.10.1
  - jq=1.6
  - tbb=2020.3
