name: bulk-rna-seq-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=3.6.3
  - r-dplyr=1.0.4
  - r-readr=1.4.0
  - bioconductor-tximport=1.14.0
  - bioconductor-genomicfeatures=1.38.0
  - rsem=1.3.3
  - salmon=1.4.0
  - fastp=0.20.1
  - star=2.7.8a
  - picard-slim=2.25.0
  - multiqc=1.9
  - jq=1.6
